services:
  paperlessngx-ai:
    image: clusterzx/paperless-ai
    container_name: PaperlessNGX-AI
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - /volume1/docker/paperlessngxai:/app/data:rw
    ports:
      - 3747:3000
    restart: on-failure:5